<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Writing my children&rsquo;s story, &ldquo;Turning Point&rdquo;, I learned more about the ethics of climate engineering than simply by reading about it. Explaining something complicated to someone who knows nothing of it forces one to think and fully comprehend a topic so that the distilled version is an accurate representation of the whole. This is the first time I&rsquo;ve had the opportunity to teach something that I&rsquo;ve learned, especially in the form of a story aimed at middle readers.">
    <title>Ryan Rowe &mdash; Turning Point</title>

    <link href="/files/css/style.css" rel="stylesheet" type="text/css">
    <?php readfile($_SERVER['DOCUMENT_ROOT'] . "/files/favicons.html") ?>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" ></script>
    <script src="/files/scripts/analytics.js"></script>
    <script src="/files/scripts/scrollbar.js"></script>
    <!-- <script src="/files/scrollbar.js"></script> -->

    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
<div class="container">
  <?php readfile($_SERVER['DOCUMENT_ROOT'] . "/files/header.html") ?>
  <article class="content offset">
    <section class="main">
    	<h1>Turning Point</h1>
    	<section class="text dropshadow">
        July 21st, 2037<br />
        <p>There aren&rsquo;t as many clouds as there used to be; it&rsquo;s quite dismal. I adored looking out to where the rough blue of the water met the smooth blue of the sky and watching the clouds saunter over the horizon like great behemoths indifferent to what&rsquo;s happening below. That&rsquo;s not really possible anymore. It seems like the drought has been going on for an eternity. The lake is a fraction of its former self and the skies are barren. Even when a parade of clouds comes marching by, it&rsquo;s too hot to sit outside for longer than a few minutes. Now that we can&rsquo;t go outside as much, Mom said that I should keep a journal although I can barely remember to do my homework so who knows how often I&rsquo;ll remember to write in here.</p>
        <p>Anyway, I remember learning about what&rsquo;s happening in history class. Mom told me about it too; she&rsquo;s a climatologist. She said it&rsquo;s called climate change. Surprisingly, a few decades ago they didn&rsquo;t even believe it was real. In 2015, the U.S. senate held a vote to decide whether climate change was real or not. Doesn&rsquo;t that seem absurd, a bunch of old men voting to decide whether a fact is true or not? Could you imaging if the senate had to vote to decide whether or not clouds exist? Well, just like clouds, climate change exists whether you believe in it or not. My teachers said that the land around here used to be covered with grass, shrubs, and trees but over time it got warmer and dryer until most of the plants turned to dust and blew away with the wind. It&rsquo;s not like this everywhere though. Places near the oceans like New York City and Louisiana have constant problems with flooding. Many cities have even had to build levees to keep the water from saturating the streets. I&rsquo;ve heard there&rsquo;s even parts of Florida that are completely underwater now. I&rsquo;m not too worried about it, I know that people like Mom are working diligently to try to fix this.</p><br />

        September 14th, 2037<br />
        <p>I&rsquo;m starting 8th grade this Wednesday. I&rsquo;m not nervous about that; however, I am nervous about Mom. She seems very anxious. She said that scientists think soon the cities on the coasts won&rsquo;t be around much longer and the droughts won&rsquo;t end any time soon. Not only that, but things all over the world are getting worse. I see her sitting with her computer late at night working. Sometimes I silently watch her from the staircase. She looks so stressed.</p><br />

        December 20th, 2037<br />
        <p>I can half-remember playing with snow when I was a kid. It&rsquo;s such a distant memory that it&rsquo;s practically like watching a movie. There hasn&rsquo;t been a white Christmas here in a long time. There&rsquo;s no snow but there&rsquo;s definitely wind. Sometimes there&rsquo;s even storms but instead of rain or snow it&rsquo;s just dust, which might be even worse. In science class they said that since so much vegetation has died, there isn&rsquo;t much holding the soil down so when the wind blows the dirt goes with it. Apparently the same thing happened a long time ago during the Dustbowl in the 1930s. Back then, it was so horrendous that people contracted dust pneumonia from inhaling too much dust. This all seems very ominous.</p>
        <p>Mom sat me down to let me know what&rsquo;s happening. She said that an international organization of scientists is trying to figure out how to stop climate change and reverse its effects. The thing is, they don&rsquo;t know if they have the right to do it. But if climate change continues, more people will die. She said that already thousands of people have died from the flooding and storms caused by the rising sea levels and warming oceans and that if we do nothing to stop it, millions of people could die. The thing is, if we do try to stop it, we could cause unintended effects and end up making it worse; millions of people could die or the next ice age could start!</p><br />

        April 1st, 2038<br />
        <p>It&rsquo;s been a long time since I&rsquo;ve written anything, I&rsquo;d almost forgotten about this journal until I saw a report about climate engineering on the news. Hearing the reporters talk about it, it seemed almost magical. They talked about a myriad of different ways that scientists could try to diminish the effects of climate change. My favorite (for obvious reasons) was cloud seeding and marine cloud brightening. Seeding involves spraying chemicals into the air over land to cause more clouds to form. The chemicals act as a catalyst, sort of as seeds that grow into cloud. The hope is that the increased number of clouds will cause it to rain more often and provide water to drought-ridden areas. Cloud brightening involves spraying seawater into the air in the oceans to make more and denser clouds. By covering the dark surface of the water with more clouds that are brighter, more sunlight will be reflected away from the surface so that the earth can stay a little cooler. I just hope they do this so I can watch the clouds drifting through the sky.</p><br />

        July 20th, 2038<br />
        <p>We&rsquo;re well into July now and there&rsquo;s been a huge heatwave ravishing the country. In parts of the south, it&rsquo;s been over 130 degrees for almost two weeks. In all of the news reports on TV, the grass looks dead and bleached blonde by the sun. There have been dozens of rampaging wildfires, many of them caused by fireworks for the 4th of July; apparently even a drought can&rsquo;t stop drunk people with explosives.</p>
        <p>It&rsquo;s terrifying. The terrain of the United States is no longer a mild forest with regions of hot and cold; it is now a land of extremes. Wildfires rage through forests while water ravages cities. Dust storms and hurricanes compete for destruction. It seems like some places are completely unlivable now. Even with rationing in effect in California, they&rsquo;ve been shipping hundreds of millions of gallons of water in just to meet demand. Is this the fate for the rest of the world?</p><br />

        August 16th, 2038<br />
        <p>Mom will be gone all of this week. She&rsquo;s going to a United Nations conference with politicians and scientists to discuss climate change. The president gave a speech a few months ago, when the heatwave was at its peak, declaring a national state of emergency and promoting climate change reversal to the country&rsquo;s top priority. Hopefully people will actually do something about it this time. In the early 2000s, when there it had not yet had much of an effect on the globe, people had the opportunity to alter the future but everyone thought someone else should deal with it, so instead they chose to push the problem to a later time.</p>
        <p>I understand that some newer countries feel it&rsquo;s wrong for them to be responsible for stopping climate change because they&rsquo;re not the ones who initially damaged the environment. I&rsquo;d be frustrated too, just like I am when my brother does something wrong but my parents punish me for it instead.</p>
        <p>My mom said they&rsquo;re meeting specifically to discuss climate engineering. The global situation is only getting worse and now there are countless lives in immediate danger. If we&rsquo;re going to try to fight this, this may be our last chance. There&rsquo;s a variety of methods that they could use to combat the warming climate but they&rsquo;re still not sure which one is the safest and most effective. Scientists have been researching hundreds of different methods of climate engineering for decades in an attempt to find the panacea we so desperately need. From storing CO2 in plants and burying them underground to launching them into space, they&rsquo;ve pretty much exhausted every avenue, leaving nothing to the imagination. It&rsquo;s even been suggested that we build a factory on the moon that makes giant reflectors to carefully position in between the earth and the sun to stop some of the sun&rsquo;s light from reaching the earth&rsquo;s surface.</p>
        <p>By the end of the conference, the leading scientists in the world will have made a final decision about what to do. They&rsquo;ll decide whether to take action to stop the self-destructive machine of climate change set in motion during the Industrial Revolution or let nature take its destructive course. Whatever they do, I hope they make the right choice.</p><br />

        August 23th, 2038<br />
        <p>My mom is back and with her she brings the conference&rsquo;s decision. It hasn&rsquo;t even been released to the media yet; the United Nations will be announcing it in a press release later tonight. She said that there were representatives from almost every country in the world present at the meeting. There were countless hours of presentations, discussions, arguments, and votes. Not only did they have to find the best scientific strategy, but they also had to grapple with the ethical implications, political complications, and the logistics of implementation. They had to find a strategy to fight climate change that every country could agree on. Climate change is a global problem and the only way to combat it is globally. Whatever action we take to alter its path affects every single person across the entire planet. It is quite possibly the only truly global issue that humanity has had to face. I&rsquo;m sure that today will be a day preserved in history for years to come. It will possibly decide the fate of the planet.</p>
        <p>A solution was proposed, a discussion was held, and a vote was taken. With an almost unanimous vote, the world has decided to attempt to derail the course of nature. Hopefully it will be better than the last time humanity interfered with nature too much, which is what started this whole mess. They decided that given the severity of the problems the world is facing and the immediate danger posed to its inhabitants, we need to take extreme, decisive action. In a combined global effort, within two months, we will begin releasing chemicals (specifically sulfate aerosols) into the stratosphere.</p>
        <p>The idea came from analysis of past ice ages. Many were caused by the explosive force of volcanoes shooting ash and gasses into the atmosphere which blocked out the sun and dramatically reduced the planet&rsquo;s temperature. Among the debris projected were sulfate compounds which scientists theorize stopped a large amount of sunlight from entering the atmosphere could stop the warming of the planet. This plan is not without risks. It is possible that the earth could be cooled too much and another ice age would begin or that introducing a chemical into the atmosphere could cause problems that we didn&rsquo;t foresee. Some are hesitant to solve climate change by pumping yet another chemical into the atmosphere but the conference decided that it is worth the risk. That&rsquo;s the problem with all of these climate engineering solutions, they&rsquo;re all untested. It&rsquo;s almost impossible to accurately test something like pumping chemicals into the atmosphere without actually doing so.</p>
        <p>They&rsquo;re confident that this is the best solution. If it&rsquo;s works, we&rsquo;ll be able to see the effects almost immediately but it will still take decades for the planet to recover from the immense damage we&rsquo;ve caused it. Hopefully, soon healing can begin.</p><br />

        October 12th, 2038<br />
        <p>Every news channel is showing the same thing. They&rsquo;re opening the first array of sulfate dispersion apparati during a huge ceremony today. The world is sitting in motionless anticipation, with hesitant hope, waiting to see what our fate will be. This could save the world or end it. Will this new technology be our saving grace or our ultimate destruction? Have we made the right decision? Our fate, whatever it may be, is immutable now and soon it will greet us.</p><br />

        <p>October 15th, 2038<br />
        Soon I&rsquo;ll finally be with the clouds again.</p>
        </section>
    </section> <!--end #welcome-->
  </article> <!-- end .content -->
  <?php include($_SERVER['DOCUMENT_ROOT'] . "/files/footer.php") ?>
</div> <!-- end .container -->
</body>
</html>
